### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by dlhxr**

### CODE REVIEW

**Comment by dlhxr** [comment]
Update to the latest version

**Comment by Rijul-Ahuja** [comment]
Hello, if you will take a look at my Knock Code lockscreen module, it credits the translators appropriately by linking to their facebook / blog / whatever. 
1. Is there any link you would like put up? Or should I leave it blank?
2. What should I write down your name as? dlhxr, or something else?
Thanks.

**Comment by dlhxr** [comment]
Haha, dlhxr is ok. You could link me to my github~

**Comment by Rijul-Ahuja** [comment]
Will be merged in a month, busy at work

**Pull request merged**
